# Generated by Django 3.1.4 on 2021-03-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boards',
            field=models.JSONField(default=dict, verbose_name='Boards'),
        ),
        migrations.AddField(
            model_name='user',
            name='threads',
            field=models.JSONField(default=dict, verbose_name='Threads'),
        ),
    ]
