# Generated by Django 3.1.7 on 2021-03-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('nonce', models.PositiveBigIntegerField(default=0, verbose_name='Nonce')),
                ('public_address', models.CharField(default=None, max_length=300, verbose_name='Public Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('creator', models.CharField(blank=True, default='Anonymous', max_length=30, null=True, verbose_name='Creator')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Link')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Thumbnail')),
                ('fileName', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='Is Private')),
                ('tag', models.CharField(default=None, max_length=10, unique=True, verbose_name='Tag')),
                ('title', models.CharField(default=None, max_length=100, unique=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Description')),
                ('maxThreads', models.IntegerField(blank=True, default=200, null=True, verbose_name='Max Threads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('wallet_address', models.CharField(default=None, max_length=255, verbose_name='Wallet Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('creator', models.CharField(blank=True, default='Anonymous', max_length=30, null=True, verbose_name='Creator')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Link')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Thumbnail')),
                ('fileName', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('isPinned', models.BooleanField(default=False, verbose_name='Is Pinned')),
                ('isPruned', models.BooleanField(default=False, verbose_name='Is Pruned')),
                ('subject', models.CharField(default=None, max_length=255, verbose_name='Subject')),
                ('text', models.TextField(blank=True, default=None, max_length=40000, null=True, verbose_name='Text')),
                ('maxPosts', models.IntegerField(default=1000, verbose_name='Max Posts')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.board', verbose_name='Board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('creator', models.CharField(blank=True, default='Anonymous', max_length=30, null=True, verbose_name='Creator')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Link')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Thumbnail')),
                ('fileName', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('text', models.TextField(blank=True, default=None, max_length=40000, verbose_name='Text')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.board', verbose_name='Board')),
                ('replyto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.post', verbose_name='Replies To')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.thread', verbose_name='Thread')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.ManyToManyField(blank=True, related_name='sub', to='core.Board', verbose_name='Sub'),
        ),
        migrations.AddField(
            model_name='user',
            name='super_sub',
            field=models.ManyToManyField(blank=True, related_name='super_sub', to='core.Board', verbose_name='Super Sub'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_boards',
            field=models.ManyToManyField(blank=True, related_name='user_boards', to='core.Board', verbose_name='User Boards'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='core.Post', verbose_name='User Posts'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_threads',
            field=models.ManyToManyField(blank=True, related_name='user_threads', to='core.Thread', verbose_name='User Threads'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_wallets',
            field=models.ManyToManyField(blank=True, related_name='user_wallets', to='core.Wallet', verbose_name='User Wallets'),
        ),
    ]
