# Generated by Django 3.1.7 on 2021-03-21 19:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_address',
            new_name='address',
        ),
        migrations.CreateModel(
            name='ERC721',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erc721', to='core.wallet', verbose_name='Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ERC20',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erc20', to='core.wallet', verbose_name='Wallet')),
            ],
        ),
    ]
