# Generated by Django 3.1.4 on 2021-03-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_boards',
            field=models.ManyToManyField(blank=True, related_name='user_boards', to='core.Board', verbose_name='User Boards'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='core.Post', verbose_name='User Posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_threads',
            field=models.ManyToManyField(blank=True, related_name='user_threads', to='core.Thread', verbose_name='User Threads'),
        ),
    ]
