# Generated by Django 3.1.7 on 2021-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_address',
            field=models.CharField(default=None, max_length=300, unique=True, verbose_name='Public Address'),
        ),
    ]
