# Generated by Django 3.1.7 on 2021-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tokenuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='address',
            field=models.CharField(default=None, max_length=255, verbose_name='Wallet Address'),
        ),
    ]
