# Generated by Django 3.1.4 on 2021-03-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_wallets',
            field=models.ManyToManyField(blank=True, related_name='user_wallets', to='core.Wallet', verbose_name='User Wallets'),
        ),
    ]
