# Generated by Django 3.1.7 on 2021-03-21 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210321_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERC1155',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erc1155', to='core.wallet', verbose_name='Wallet')),
            ],
        ),
    ]
