# Generated by Django 3.1.7 on 2021-04-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nft_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=10000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True, verbose_name='Text'),
        ),
    ]
