# Generated by Django 3.1.7 on 2021-05-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210427_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.IntegerField(default=0, verbose_name='Posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='Shares'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='thread',
            name='posts',
            field=models.IntegerField(default=0, verbose_name='Posts'),
        ),
        migrations.AddField(
            model_name='thread',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='Shares'),
        ),
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='core.board', verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='post',
            name='replyto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='core.post', verbose_name='Replies To'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='core.thread', verbose_name='Thread'),
        ),
    ]
