# Generated by Django 3.1.7 on 2021-05-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210507_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='replyto',
            new_name='repliesto',
        ),
    ]
