# Generated by Django 3.1.4 on 2021-01-24 12:55

import boards.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('creator', models.CharField(blank=True, default='Anonymous', max_length=255, null=True, verbose_name='Creator')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('fileName', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Thumbnail')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Image')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Link')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='Is Private')),
                ('tag', models.CharField(default=None, max_length=10, unique=True, verbose_name='Tag')),
                ('title', models.CharField(default=None, max_length=100, unique=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Description')),
                ('maxThreads', models.IntegerField(blank=True, default=200, null=True, verbose_name='Max Threads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('creator', models.CharField(blank=True, default='Anonymous', max_length=255, null=True, verbose_name='Creator')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('fileName', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Thumbnail')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Image')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Link')),
                ('text', models.TextField(blank=True, default=None, max_length=20000, null=True, verbose_name='Text')),
                ('subject', models.CharField(default=None, max_length=255, verbose_name='Subject')),
                ('isPinned', models.BooleanField(default=False, verbose_name='Is Pinned')),
                ('isPruned', models.BooleanField(default=False, verbose_name='Is Pruned')),
                ('maxPosts', models.IntegerField(default=1000, verbose_name='Max Posts')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='boards.board', verbose_name='Board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('creator', models.CharField(blank=True, default='Anonymous', max_length=255, null=True, verbose_name='Creator')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('fileName', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Thumbnail')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Image')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Link')),
                ('text', models.TextField(blank=True, default=None, max_length=20000, verbose_name='Text')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.board', verbose_name='Board')),
                ('replyto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.post', verbose_name='Replies To')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.thread', verbose_name='Thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
