# Generated by Django 3.1.4 on 2021-01-21 21:47

import boards.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='Is Private')),
                ('isOfficial', models.BooleanField(default=False, verbose_name='Is Official')),
                ('tag', models.CharField(default=None, max_length=10, verbose_name='Tag')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Decription')),
                ('maxThreads', models.IntegerField(default=200, verbose_name='Maximum number of Threads')),
                ('file_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Thumbnail')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Image')),
                ('link', models.URLField(blank=True, default=None, null=True, verbose_name='Board link')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('creator', models.CharField(blank=True, default='Anonymous', max_length=255, null=True, verbose_name='Creator')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('isPinned', models.BooleanField(default=False, verbose_name='Is Pinned')),
                ('subject', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Subject')),
                ('maxPosts', models.IntegerField(default=500, verbose_name='Maximum number of Posts')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.board', verbose_name='Parent Board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('creator', models.CharField(blank=True, default='Anonymous', max_length=255, null=True, verbose_name='Creator')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('isOP', models.BooleanField(default=False, verbose_name='Is OP')),
                ('isPinned', models.BooleanField(default=False, verbose_name='Is Pinned')),
                ('text', models.TextField(default=None, max_length=20000, verbose_name='Text')),
                ('file_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File Name')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Thumbnail')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Image')),
                ('replies', models.ManyToManyField(blank=True, related_name='_post_replies_+', to='boards.Post', verbose_name='Replies')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.thread', verbose_name='Parent Thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
