# Generated by Django 3.1.4 on 2021-01-25 18:23

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='imageV',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=None, null=True, upload_to='', verbose_name='ImageV'),
        ),
        migrations.AddField(
            model_name='post',
            name='imageV',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=None, null=True, upload_to='', verbose_name='ImageV'),
        ),
        migrations.AddField(
            model_name='thread',
            name='imageV',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=None, null=True, upload_to='', verbose_name='ImageV'),
        ),
    ]
