# Generated by Django 3.1.4 on 2021-01-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='is_board',
            new_name='is_private',
        ),
        migrations.RemoveField(
            model_name='board',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_post',
        ),
    ]
