# Generated by Django 3.1.4 on 2021-01-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='replyto',
        ),
    ]
