# Generated by Django 3.1.4 on 2021-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='maxThreads',
            field=models.IntegerField(default=200, verbose_name='Max Threads'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='maxPosts',
            field=models.IntegerField(default=500, verbose_name='Max Posts'),
        ),
    ]
