# Generated by Django 3.1.4 on 2021-01-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='board',
            name='tag',
            field=models.CharField(default=None, max_length=10, unique=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
