# Generated by Django 3.1.4 on 2021-01-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='ppoi',
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
