# Generated by Django 3.1.4 on 2021-01-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210122_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Title'),
        ),
    ]
