# Generated by Django 3.1.4 on 2021-01-20 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_auto_20210119_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, related_name='_thread_posts_+', to='boards.Thread')),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='pages',
        ),
        migrations.AddField(
            model_name='board',
            name='threads',
            field=models.ManyToManyField(blank=True, related_name='_board_threads_+', to='boards.Board'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
