# Generated by Django 3.1.4 on 2021-01-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_post_replyto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replyto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.post', verbose_name='Replies To'),
        ),
    ]
