# Generated by Django 3.1.4 on 2021-01-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210120_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='posts',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
