# Generated by Django 3.1.4 on 2021-01-22 10:15

import boards.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210122_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file_name',
            new_name='fileName',
        ),
        migrations.AddField(
            model_name='board',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='creator',
            field=models.CharField(blank=True, default='Anonymous', max_length=255, null=True, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='board',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='thread',
            name='fileName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='thread',
            name='isOP',
            field=models.BooleanField(default=False, verbose_name='Is OP'),
        ),
        migrations.AddField(
            model_name='thread',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='_thread_replies_+', to='boards.Thread', verbose_name='Replies'),
        ),
        migrations.AddField(
            model_name='thread',
            name='text',
            field=models.TextField(default=None, max_length=20000, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='thread',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to, verbose_name='Thumbnail'),
        ),
    ]
