# Generated by Django 3.1.4 on 2021-01-20 16:01

import boards.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_post_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='creator',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='creator',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='getID',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='_post_replies_+', to='boards.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=20000),
        ),
    ]
