# Generated by Django 3.1.4 on 2021-01-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210123_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='maxThreads',
            field=models.IntegerField(blank=True, default=200, null=True, verbose_name='Max Threads'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
