# Generated by Django 3.1.4 on 2021-01-20 18:04

import boards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0006_auto_20210120_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='name',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='board',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='getID',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to),
        ),
        migrations.AddField(
            model_name='board',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='is_op',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='getID',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=boards.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=None, max_length=20000),
        ),
        migrations.CreateModel(
            name='ThreadManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
