# Generated by Django 3.1.4 on 2021-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210122_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='isOfficial',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is Official'),
        ),
    ]
