# Generated by Django 3.1.4 on 2021-01-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210120_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.AddField(
            model_name='thread',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
