# Generated by Django 3.1.4 on 2021-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210124_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='maxPosts',
            field=models.IntegerField(default=1000, verbose_name='Max Posts'),
        ),
    ]
