# Generated by Django 3.1.4 on 2021-01-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20210122_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='isOfficial',
        ),
    ]
