# Generated by Django 3.1.4 on 2021-01-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_remove_board_isofficial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isPinned',
        ),
    ]
