# Generated by Django 3.1.4 on 2021-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_thread_ispruned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fileName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='fileName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='File name'),
        ),
    ]
