# Generated by Django 3.1.4 on 2021-01-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20210122_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isOP',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='isOP',
        ),
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.board', verbose_name='Parent Board'),
        ),
        migrations.AddField(
            model_name='post',
            name='replies_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='_post_replies_to_+', to='boards.Post', verbose_name='Replies To'),
        ),
        migrations.AddField(
            model_name='thread',
            name='replies_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='_thread_replies_to_+', to='boards.Thread', verbose_name='Replies To'),
        ),
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, related_name='_post_replies_+', to='boards.Post', verbose_name='Replies'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, related_name='_thread_replies_+', to='boards.Thread', verbose_name='Replies'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=20000, null=True, verbose_name='Text'),
        ),
    ]
